extra/.bashrc
[check docs noob](https://github.com/ajeetdsouza/zoxide?tab=readme-ov-file#flags)
=> ZOXIDE ALIAS WHAT IS THIS WHAT ARE U ON

Readme.md, uninstall.sh
=> feat: implement uninstall script

.github/contributing.md
adds guidelines for commit messages / pr titles
=> docs: add commit messages / pr titles guidelines

.github/contributing.md
removes a rule from the guidelines
=> docs: remove a rule

install.sh
Improved error handling (b30f267b353cc5e91aa55da59eccacbb26d9bae5) and added `base-devel` installation before paru stuff.
=> refact(sh): better error handling + build deps for paru

install.sh, uninstall.sh
=> refact(sh): use symlinks instead of hard-copying files

install.sh
=> fix(sh): create `/usr/share/icons/default/index.theme` before editing it

extra/vscode/settings.json
=> feat: update code settings

uninstall.sh
=> fix: redirect output to /dev/null

Readme.md
=> docs: implement uninstall section

.github/PULL_REQUEST_TEMPLATE.md
=> refact: Remove options from template

Readme.md
=> docs: add on to the dwm sections

extra/fastfetch/config.jsonc
=> refact: use users actual username and hostname

install.sh
=> fix: make makepkg non-user-interactive

install.sh, uninstall.sh
=> fix: make backups in .config instead of the users home dir

uninstall.sh
=> chore: re-order functions

Readme.md
=> docs: update uninstalling section

Readme.md
=> docs: add a new note

extra/.zshrc
=> fix: fix history saving

extra/.zshrc
=> fix: fix history saving 2

suckless/dwm/dwm.c
=> refact: remove window snapping in floating

extra/picom/picom.conf
=> feat: remove opacity for dmenu

install.sh, uninstall.sh, update.sh
=> Revert "fix: number of steps"
